export const COLLECTIONS = {
  USERS: 'users',
  AUTH_SESSIONS: 'authsessions',
  PROJECTS: 'projects',
  BLOG_POSTS: 'blogposts',
  SERVICES: 'services',
  TEAM_MEMBERS: 'teammembers',
  CONTACTS: 'contacts',
  CAREERS: 'careers',
  PUBLICATIONS: 'publications',
    JOB_APPLICATIONS: 'jobapplications',
  OTPS: 'otps',
  SITE_SETTINGS: 'sitesettings',
  CAREER_CATEGORIES: 'careercategories',
  BLOG_CATEGORIES: 'blogcategories',
  PROJECT_CATEGORIES: 'projectcategories',
} as const;
